# Generated by Django 2.2.23 on 2021-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
